export enum BookCategory {
  FICTION = "FICTION",
  NON_FICTION = "NON_FICTION",
  SCIENCE = "SCIENCE",
  TECHNOLOGY = "TECHNOLOGY",
  HISTORY = "HISTORY",
  BIOGRAPHY = "BIOGRAPHY",
  BUSINESS = "BUSINESS",
  SELF_HELP = "SELF_HELP",
  HEALTH = "HEALTH",
  EDUCATION = "EDUCATION",
  RELIGION = "RELIGION",
  ART = "ART",
  CHILDREN = "CHILDREN",
  COMICS = "COMICS",
  POETRY = "POETRY",
  REFERENCE = "REFERENCE",
}

export enum Role{
    ADMIN = "ADMIN",
    USER = "USER"
}